# Generated by Django 2.2.6 on 2019-10-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='作者的姓名')),
            ],
            options={
                'verbose_name_plural': '03-作者表',
                'db_table': '03-作者表',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='出版社的名称')),
            ],
            options={
                'verbose_name_plural': '02-出版社表',
                'db_table': '02-出版社表',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32, verbose_name='图书名称')),
                ('category', models.IntegerField(choices=[(1, 'Python'), (2, 'Go'), (3, 'Linux')], verbose_name='图书的类别')),
                ('pub_time', models.DateField(verbose_name='图书的出版日期')),
                ('author', models.ManyToManyField(to='SerDemo.Author')),
                ('publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SerDemo.Publisher')),
            ],
            options={
                'verbose_name_plural': '01-图书表',
                'db_table': '01-图书表',
            },
        ),
    ]
