# Generated by Django 2.2.6 on 2019-10-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authDemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(1, 'vip'), (2, 'vvip'), (3, '普通')], default=3, verbose_name='权限'),
        ),
    ]
